{{- $fullName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service-prod
  labels:
    app: {{ template "blue-green.name" . }}
    chart: {{ template "blue-green.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 9080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ template "blue-green.name" . }}
    release: {{ .Release.Name }}
    slot: {{ .Values.productionSlot }}
